#!/bin/bash

# Update package list and install HAProxy if not already installed
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
cat <<EOT | sudo tee /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    option  redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 429103-web-01 54.173.95.202:80 check
    server 429103-web-02 54.175.123.89:80 check

listen hbnb
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    stats auth admin:admin
EOT

# Enable and start HAProxy service
sudo systemctl enable haproxy
sudo systemctl start haproxy

# Output status of HAProxy service
sudo systemctl status haproxy
